
export const fontList = [
    "Arial",
    "Arial Black",
    "Bahnschrift",
    "Baskerville Old Face",
    "Bauhaus 93",
    "Bell MT",
    "Berlin Sans FB",
    "Bernard MT Condensed",
    "Book Antiqua",
    "Bookman Old Style",
    "Bradley Hand ITC",
    "Broadway",
    "Brush Script MT",
    "Calibri",
    "Calisto MT",
    "Cambria",
    "Candara",
    "Century",
    "Century Gothic",
    "Century Schoolbook",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Cooper Black",
    "Corbel",
    "Courier New",
    "Dubai",
    "Ebrima",
    "Edwardian Script ITC",
    "Elephant",
    "Engravers MT",
    "Eras ITC",
    "Felix Titling",
    "Franklin Gothic Medium",
    "Freestyle Script",
    "Futura",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gill Sans MT",
    "Gloucester MT Extra Condensed",
    "Goudy Old Style",
    "Haettenschweiler",
    "Harlow Solid Italic",
    "Harrington",
    "High Tower Text",
    "Impact",
    "Imprint MT Shadow",
    "Ink Free",
    "Jokerman",
    "Juice ITC",
    "Kristen ITC",
    "Kunstler Script",
    "Lucida Bright",
    "Lucida Calligraphy",
    "Lucida Console",
    "Lucida Fax",
    "Lucida Handwriting",
    "Lucida Sans",
    "Lucida Sans Typewriter",
    "Lucida Sans Unicode",
    "Lato Thin",
    "Lato Thin Italic",
    "Lato Light",
    "Lato Light Italic",
    "Lato Regular",
    "Lato Italic",
    "Lato Medium",
    "Lato Medium Italic",
    "Lato Semibold",
    "Lato Semibold Italic",
    "Lato Bold",
    "Lato Bold Italic",
    "Lato Heavy",
    "Lato Heavy Italic",
    "Lato Black",
    "Lato Black Italic",
    "Maiandra GD",
    "Malgun Gothic",
    "Marlett",
    "Matura MT Script Capitals",
    "Microsoft Himalaya",
    "Microsoft JhengHei",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft Uighur",
    "Microsoft YaHei",
    "Microsoft Yi Baiti",
    "MingLiU-ExtB",
    "Mistral",
    "Modern No. 20",
    "Mongolian Baiti",
    "Monotype Corsiva",
    "MS Gothic",
    "MS PGothic",
    "MS Reference Sans Serif",
    "MS Reference Specialty",
    "MS UI Gothic",
    "MT Extra",
    "MV Boli",
    "Nirmala UI",
    "Old English Text MT",
    "Onyx",
    "Palatino Linotype",
    "Papyrus",
    "Perpetua",
    "Playbill",
    "Poor Richard",
    "Pristina",
    "Rage Italic",
    "Ravie",
    "Rockwell",
    "Rockwell Condensed",
    "Rockwell Extra Bold",
    "Script MT Bold",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Symbol",
    "Showcard Gothic",
    "Sitka",
    "Snap ITC",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Tempus Sans ITC",
    "Times New Roman",
    "Trebuchet MS",
    "Tw Cen MT",
    "Verdana",
    "Viner Hand ITC",
    "Vivaldi",
    "Vladimir Script",
    "Webdings",
    "Wide Latin",
    "Wingdings",
    "Wingdings 2",
    "Wingdings 3"
  ]
  


  export const  sampleLyrics = 
  `
  --- Paste your lyrics here ---
  
  --- Sample Format ---
  You were the Word at the beginning
  One with  God the  Lord Most High
  Your hidden glory in creation
  Now revealed in You our Christ
  
  What a beautiful Name it is
  What a beautiful Name it is 
  The Name of Jesus Christ my King
   
  What a beautiful Name it is
  Nothing compares to this
  What a beautiful Name it is 
  The Name of Jesus
  
  You didn’t want heaven without us
  So Jesus You brought heaven down
  My sin was great Your love was greater
  What could separate us now?
  `
  